.TH favorites.cleanup 3 "29 Jan 2021" "pyopenTIDAL 1.0.1" "pyopenTIDAL Manual"
.SH NAME
favorites.cleanup \- Deallocate a container from heap 
.SH SYNOPSIS
.B import openTIDAL

.nf
.BI "class favorites (" object "):"
.BI "    def cleanup (" self ", " content ")"
.fi
.SH DESCRIPTION
After using a OTContainer returned from a service function one needs to deallocate it.
Up to this point values inside the container are still allocated in heap. The container itself
is also allocated in heap and needs to be freed.
.SH RETURN VALUE
None
.SH "SEE ALSO" 
.BR favorites.get "(3), " favorites.deleteItem "(3), " favorites.addItems "(3), "
.BR favorites.addItems "(3), " base.getStandard "(3), " stream.getTrackStream "(3) "
