.TH json.isNull 3 "29 Jan 2021" "pyopenTIDAL 1.0.1" "pyopenTIDAL Manual"
.SH NAME
json.isNull \- Check for a null value
.SH SYNOPSIS
.B import openTIDAL

.nf
.BI "class json (" object "):"
.BI "    def isNull (" self ", " jsonContainer ")"
.fi
.SH DESCRIPTION
Check an object for a json null value.
.SH RETURN VALUE
Returns either 1 or 0 as a boolean.
.SH "SEE ALSO"
.BR json.isString "(3), " json.isArray "(3), " json.isBool "(3), "
.BR json.isTrue "(3), " json.isObject "(3), " json.isNumber "(3) "
