.TH json.isString 3 "29 Jan 2021" "pyopenTIDAL 1.0.1" "pyopenTIDAL Manual"
.SH NAME
json.isString \- Check for a string value
.SH SYNOPSIS
.B import openTIDAL

.nf
.BI "class json (" object "):"
.BI "    def isString (" self ", " jsonContainer ")"
.fi
.SH DESCRIPTION
Represents a string value. Check an object for a json string value.
.SH RETURN VALUE
Returns either 1 or 0 as a boolean.
.SH "SEE ALSO"
.BR json.isTrue "(3), " json.isArray "(3), " json.isBool "(3), "
.BR json.isNull "(3), " json.isObject "(3), " json.isNumber "(3) "
