.TH json.isArray 3 "29 Jan 2021" "pyopenTIDAL 1.0.1" "pyopenTIDAL Manual"
.SH NAME
json.isArray \- Check for an array value
.SH SYNOPSIS
.B import openTIDAL

.nf
.BI "class json (" object "):"
.BI "    def isArray (" self ", " jsonContainer ")"
.fi
.SH DESCRIPTION
Represent an array value. Check for an array value.
.SH RETURN VALUE
Returns either 1 or 0 as a boolean.
.SH "SEE ALSO"
.BR json.isString "(3), " json.isInvalid "(3), " json.isBool "(3), "
.BR json.isNull "(3), " json.isObject "(3), " json.isNumber "(3) "
