.TH playlist.moveItem 3 "29 Jan 2021" "pyopenTIDAL 1.0.1" "pyopenTIDAL Manual"
.SH NAME
playlist.moveItem \- Move an artefact in a playlist
.SH SYNOPSIS
.B import openTIDAL

.nf
.BI "class playlist (" object "):"
.BI "    def moveItem (" self ", " session ", " contentId ", " index ", " toIndex ", " threadHandle ")"
.fi
.SH DESCRIPTION
The OTServiceMovePlaylistItem service function moves an artefact in a playlist.

A playlist starts from 0.
.SH RETURN VALUE
\fIenums.status(7)\fP
.SH "SEE ALSO" 
.BR json.getObject "(3), " playlist.deleteItem "(3), " playlist.moveItem "(3), "
.BR playlist.addItem "(3), " playlist.addItems "(3), " session.login "(3) "
