.TH session.getHandle 3 "29 Jan 2021" "pyopenTIDAL 1.0.1" "pyopenTIDAL Manual"
.SH NAME
session.getHandle \- Get the main http handle
.SH SYNOPSIS
.B import openTIDAL

.nf
.BI "class session (" object "):"
.BI "    def getHandle (" self ")" 
.fi
.SH DESCRIPTION
Call this function to get the main http handle allocated by the libopenTIDAL session.
If you perform service requests in an additional thread, you \fBmust\fP use a new http-handle.
However, you can use a handle persistently.
.SH RETURN VALUE
If successful, the http-handle gets returned.
.SH "SEE ALSO"
.BR session.login "(3), " session.clientPair "(3), " session.verbose "(3), "
.BR session.changeQuality "(3), " session.writeChanges "(3), " session.manualRefresh "(3) "
